### ISSUE TITLE
Tilemap Mockup / Background mockup

### ISSUE THREAD

**Issue by XOR-SABER** [rumkkee/Simple_Roguelike#15]
Developers should have an Idea of the playable space

**Comment by KyleLynnDev** [comment]
![image](https://github.com/user-attachments/assets/87c5ad19-4b39-4a41-80ea-e0e23b07108d)
![image](https://github.com/user-attachments/assets/9d42411f-9435-42dc-81c2-470076ed0e05)
![image](https://github.com/user-attachments/assets/41ae5109-1c05-45ed-9fef-40ec876bff48)
