### ISSUE TITLE
Item RNG

### ISSUE THREAD

**Issue by BhavikChand** [rumkkee/Simple_Roguelike#48]
2 Items in the shop at static. 4 items in the shop are randomized.

The 4 items we want to be randomized are as follows: Health, Attack, Armor, Speed

The 4 items to be randomized will be evaluated in Tiers 1 through 5.

Modifier and Cost are static, they do not change based off the RNG value generated.

**Comment by XOR-SABER** [comment]
Not planned, simplifying shop
