### ISSUE TITLE
Tilesets / environment assets and sprites 

### ISSUE THREAD

**Issue by KyleLynnDev** [rumkkee/Simple_Roguelike#9]
As a developer I want modular assets I can use to create a nice world for the player. 

As a player I want nice things to open the game and be presented with pleasant aesthetic experiences and objects to look at, interact with, etc.

**Comment by KyleLynnDev** [comment]
Need to start with placeholder assets

**Comment by XOR-SABER** [comment]
Closed with issue #58, we are doing sprites.
